#define ROCKFORD_SPRITES_QTD 41
#define MAGIC_WALL_SPRITES_QTD 4
#define FIREFLY_SPRITES_QTD 8
#define BUTTERFLY_SPRITES_QTD 8
#define AMOEBA_SPRITES_QTD 8
#define DIAMOND_SPRITES_QTD 8
#define EXIT_SPRITES_QTD 2
